"use client"

import type { Booking, ScheduleItem } from "@/lib/types"
import { GlassCard } from "@/components/ui/glass-card"
import { PaymentBadge } from "@/components/ui/payment-badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { mockDrivers } from "@/lib/mock-data"
import { Calendar, MapPin, Users, Phone, Car, Printer, MessageCircle, ChevronLeft, ChevronRight } from "lucide-react"
import { useState, useMemo } from "react"
import { useToast } from "@/hooks/use-toast"

interface OperationsViewProps {
  bookings: Booking[]
  onSelect: (booking: Booking) => void
}

export function OperationsView({ bookings, onSelect }: OperationsViewProps) {
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split("T")[0])
  const { toast } = useToast()

  // Generate schedule items from bookings for the selected date
  const dailySchedule = useMemo(() => {
    const todayBookings = bookings.filter((b) => b.date === selectedDate && b.status !== "cancelled")

    // Convert bookings to schedule items, sorted by pickup time
    return todayBookings
      .map(
        (b): ScheduleItem => ({
          id: b.id,
          booking_id: b.id,
          time: b.pickup_time || "09:00",
          name: b.name,
          package_title: b.package_title,
          guests: b.guests,
          driver_name: b.driver_name,
          driver_phone: mockDrivers.find((d) => d.id === b.driver_id)?.phone,
          pickup_location: b.pickup_location || "TBD",
          phone_number: b.phone_number,
          special_notes: b.notes,
          activity_type: b.activity_type,
          payment_status: b.payment_status,
        }),
      )
      .sort((a, b) => a.time.localeCompare(b.time))
  }, [bookings, selectedDate])

  const handlePrintManifest = () => {
    // Simulated print - in production this would generate a PDF
    const printWindow = window.open("", "_blank")
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Daily Manifest - ${new Date(selectedDate).toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}</title>
            <style>
              body { font-family: system-ui, -apple-system, sans-serif; padding: 40px; }
              h1 { color: #C19B76; margin-bottom: 8px; }
              h2 { color: #666; font-weight: normal; margin-top: 0; }
              table { width: 100%; border-collapse: collapse; margin-top: 24px; }
              th, td { padding: 12px; text-align: left; border-bottom: 1px solid #eee; }
              th { background: #f8f8f8; font-weight: 600; }
              .badge { display: inline-block; padding: 4px 8px; border-radius: 12px; font-size: 12px; }
              .paid { background: #dcfce7; color: #166534; }
              .deposit { background: #fef3c7; color: #92400e; }
              .unpaid { background: #fee2e2; color: #991b1b; }
            </style>
          </head>
          <body>
            <h1>MARRAGAFAY</h1>
            <h2>Daily Operations Manifest</h2>
            <p><strong>Date:</strong> ${new Date(selectedDate).toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}</p>
            <p><strong>Total Bookings:</strong> ${dailySchedule.length}</p>
            <table>
              <thead>
                <tr>
                  <th>Time</th>
                  <th>Guest</th>
                  <th>Package</th>
                  <th>Pax</th>
                  <th>Pickup</th>
                  <th>Driver</th>
                  <th>Phone</th>
                  <th>Payment</th>
                </tr>
              </thead>
              <tbody>
                ${dailySchedule
          .map(
            (item) => `
                  <tr>
                    <td><strong>${item.time}</strong></td>
                    <td>${item.name}</td>
                    <td>${item.package_title}</td>
                    <td>${item.guests}</td>
                    <td>${item.pickup_location}</td>
                    <td>${item.driver_name || "-"}</td>
                    <td>${item.phone_number}</td>
                    <td><span class="badge ${item.payment_status}">${item.payment_status?.toUpperCase()}</span></td>
                  </tr>
                `,
          )
          .join("")}
              </tbody>
            </table>
            <p style="margin-top: 40px; color: #999; font-size: 12px;">Generated by Marragafay Admin Dashboard</p>
          </body>
        </html>
      `)
      printWindow.document.close()
      printWindow.print()
    }
    toast({
      title: "Manifest Printed",
      description: `Daily manifest for ${new Date(selectedDate).toLocaleDateString()} has been sent to printer.`,
    })
  }

  const handleDateChange = (direction: "prev" | "next") => {
    const date = new Date(selectedDate)
    date.setDate(date.getDate() + (direction === "next" ? 1 : -1))
    setSelectedDate(date.toISOString().split("T")[0])
  }

  const handleWhatsApp = (phone: string, name: string) => {
    const cleanPhone = phone.replace(/[^0-9]/g, "")
    const message = encodeURIComponent(`Hello ${name}, this is Marragafay. We'll be picking you up soon!`)
    window.open(`https://wa.me/${cleanPhone}?text=${message}`, "_blank")
  }

  const findBookingById = (id: string) => bookings.find((b) => b.id === id)

  return (
    <div className="space-y-6">
      {/* Date Selector & Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <Button
            variant="outline"
            size="icon"
            className="rounded-xl bg-white border-slate-200"
            onClick={() => handleDateChange("prev")}
          >
            <ChevronLeft className="w-4 h-4" />
          </Button>
          <div className="flex items-center gap-2 px-4 py-2 rounded-xl bg-white border border-slate-200">
            <Calendar className="w-4 h-4 text-muted-foreground" />
            <Input
              type="date"
              value={selectedDate}
              onChange={(e) => setSelectedDate(e.target.value)}
              className="border-0 bg-transparent p-0 h-auto w-auto text-center font-medium"
            />
          </div>
          <Button
            variant="outline"
            size="icon"
            className="rounded-xl bg-white border-slate-200"
            onClick={() => handleDateChange("next")}
          >
            <ChevronRight className="w-4 h-4" />
          </Button>
        </div>

        <Button
          className="rounded-xl bg-[#C19B76] hover:bg-[#A67C52] shadow-lg shadow-[#C19B76]/20"
          onClick={handlePrintManifest}
        >
          <Printer className="w-4 h-4 mr-2" />
          Print Manifest
        </Button>
      </div>

      {/* Summary Cards - Using solid variant */}
      <div className="grid grid-cols-3 gap-3">
        <GlassCard variant="solid" className="text-center">
          <p className="text-3xl font-bold text-[#C19B76]">{dailySchedule.length}</p>
          <p className="text-xs text-muted-foreground mt-1">Total Pickups</p>
        </GlassCard>
        <GlassCard variant="solid" className="text-center">
          <p className="text-3xl font-bold text-emerald-600">
            {dailySchedule.reduce((sum, item) => sum + item.guests, 0)}
          </p>
          <p className="text-xs text-muted-foreground mt-1">Total Guests</p>
        </GlassCard>
        <GlassCard variant="solid" className="text-center">
          <p className="text-3xl font-bold text-amber-600">{dailySchedule.filter((s) => !s.driver_name).length}</p>
          <p className="text-xs text-muted-foreground mt-1">Unassigned</p>
        </GlassCard>
      </div>

      {/* Timeline */}
      {dailySchedule.length === 0 ? (
        <GlassCard variant="solid" className="text-center py-12">
          <Calendar className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
          <h3 className="font-semibold text-lg">No Bookings</h3>
          <p className="text-muted-foreground text-sm mt-1">There are no confirmed bookings for this date.</p>
        </GlassCard>
      ) : (
        <div className="space-y-4">
          {dailySchedule.map((item, index) => {
            const booking = findBookingById(item.booking_id || "")
            return (
              <div key={item.id} className="flex gap-4">
                {/* Time Column */}
                <div className="flex flex-col items-center">
                  <div className="w-16 text-center">
                    <span className="text-lg font-bold">{item.time}</span>
                  </div>
                  {index < dailySchedule.length - 1 && <div className="w-0.5 flex-1 bg-slate-200 my-2" />}
                </div>

                {/* Card - Using solid variant */}
                <GlassCard
                  variant="solid"
                  hover
                  className="flex-1 cursor-pointer"
                  onClick={() => booking && onSelect(booking)}
                >
                  <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
                    <div className="flex-1 space-y-2">
                      <div className="flex items-center gap-2 flex-wrap">
                        <h4 className="font-semibold text-lg">{item.name}</h4>
                        {item.payment_status && <PaymentBadge status={item.payment_status} />}
                      </div>
                      <p className="text-sm text-muted-foreground">{item.package_title}</p>

                      <div className="flex flex-wrap gap-x-4 gap-y-1 text-sm">
                        <span className="flex items-center gap-1.5 text-muted-foreground">
                          <Users className="w-3.5 h-3.5" />
                          {item.guests} guests
                        </span>
                        <span className="flex items-center gap-1.5 text-muted-foreground">
                          <MapPin className="w-3.5 h-3.5" />
                          {item.pickup_location}
                        </span>
                        {item.driver_name ? (
                          <span className="flex items-center gap-1.5 text-emerald-600">
                            <Car className="w-3.5 h-3.5" />
                            {item.driver_name}
                          </span>
                        ) : (
                          <span className="flex items-center gap-1.5 text-amber-600">
                            <Car className="w-3.5 h-3.5" />
                            No driver assigned
                          </span>
                        )}
                      </div>

                      {item.special_notes && (
                        <p className="text-xs bg-amber-50 text-amber-700 px-3 py-1.5 rounded-lg inline-block border border-amber-100">
                          Note: {item.special_notes}
                        </p>
                      )}
                    </div>

                    {/* Quick Actions */}
                    <div className="flex gap-2">
                      <Button
                        size="sm"
                        variant="outline"
                        className="rounded-xl bg-emerald-50 border-emerald-200 text-emerald-700 hover:bg-emerald-100"
                        onClick={(e) => {
                          e.stopPropagation()
                          handleWhatsApp(item.phone_number || "", item.name)
                        }}
                      >
                        <MessageCircle className="w-4 h-4" />
                        <span className="hidden sm:inline ml-2">WhatsApp</span>
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        className="rounded-xl bg-white border-slate-200"
                        onClick={(e) => {
                          e.stopPropagation()
                          window.open(`tel:${item.phone_number}`, "_self")
                        }}
                      >
                        <Phone className="w-4 h-4" />
                        <span className="hidden sm:inline ml-2">Call</span>
                      </Button>
                    </div>
                  </div>
                </GlassCard>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
