import type {
  Booking,
  Package,
  DashboardStats,
  ScheduleItem,
  BookingTrend,
  Activity,
  BlogPost,
  Testimonial,
  Driver,
  Resource,
} from "./types"

export const mockDrivers: Driver[] = [
  { id: "d1", name: "Hassan Amrani", phone: "+212 661 234 567", vehicle: "Toyota Land Cruiser", is_available: true },
  { id: "d2", name: "Youssef Benali", phone: "+212 662 345 678", vehicle: "Mercedes V-Class", is_available: true },
  { id: "d3", name: "Karim Tazi", phone: "+212 663 456 789", vehicle: "Range Rover", is_available: true },
  { id: "d4", name: "Omar Fassi", phone: "+212 664 567 890", vehicle: "Ford Transit", is_available: false },
]

export const mockResources: Resource[] = [
  { id: "r1", type: "quad", name: "Quads", total_count: 20 },
  { id: "r2", type: "camel", name: "Camels", total_count: 30 },
  { id: "r3", type: "buggy", name: "Buggies", total_count: 8 },
  { id: "r4", type: "horse", name: "Horses", total_count: 15 },
  { id: "r5", type: "balloon", name: "Hot Air Balloons", total_count: 2 },
]

export const mockBookings: Booking[] = [
  {
    id: "1",
    customer_name: "Alexandra Chen",
    email: "alexandra@email.com",
    phone: "+212 655-0123",
    package_title: "VIP Desert Experience",
    status: "confirmed",
    date: "2025-12-02",
    guests: 4,
    total_price: 24000,
    notes: "Anniversary celebration, needs champagne setup",
    payment_status: "paid",
    amount_paid: 24000,
    remaining_balance: 0,
    driver_id: "d2",
    driver_name: "Youssef Benali",
    pickup_time: "14:00",
    pickup_location: "La Mamounia Hotel",
    activity_type: "camel",
  },
  {
    id: "2",
    customer_name: "Marcus Thompson",
    email: "marcus.t@email.com",
    phone: "+212 677 900123",
    package_title: "Premium Sunset Tour",
    status: "pending",
    date: "2025-12-03",
    guests: 2,
    total_price: 8000,
    payment_status: "deposit",
    amount_paid: 2000,
    remaining_balance: 6000,
    pickup_time: "15:30",
    pickup_location: "Riad Noir d'Ivoire",
    activity_type: "quad",
  },
  {
    id: "3",
    customer_name: "Sofia Rodriguez",
    email: "sofia.r@email.com",
    phone: "+212 612 345 678",
    package_title: "Basic Discovery",
    status: "confirmed",
    date: "2025-11-30",
    guests: 6,
    total_price: 9000,
    payment_status: "paid",
    amount_paid: 9000,
    remaining_balance: 0,
    driver_id: "d1",
    driver_name: "Hassan Amrani",
    pickup_time: "09:00",
    pickup_location: "Riad Jnane Mogador, Marrakech",
    activity_type: "camel",
  },
  {
    id: "4",
    customer_name: "James Wilson",
    email: "jwilson@email.com",
    phone: "+212 655-0456",
    package_title: "VIP Desert Experience",
    status: "pending",
    date: "2025-12-04",
    guests: 2,
    total_price: 12000,
    payment_status: "unpaid",
    amount_paid: 0,
    remaining_balance: 12000,
    activity_type: "buggy",
  },
  {
    id: "5",
    customer_name: "Emma Laurent",
    email: "emma.l@email.com",
    phone: "+212 6 12 34 56 78",
    package_title: "Premium Sunset Tour",
    status: "cancelled",
    date: "2025-11-28",
    guests: 4,
    total_price: 16000,
    payment_status: "unpaid",
    amount_paid: 0,
    remaining_balance: 16000,
    activity_type: "quad",
  },
  {
    id: "6",
    customer_name: "Oliver Schmidt",
    email: "o.schmidt@email.com",
    phone: "+212 661 12345678",
    package_title: "Basic Discovery",
    status: "confirmed",
    date: "2025-11-30",
    guests: 3,
    total_price: 4500,
    payment_status: "deposit",
    amount_paid: 1500,
    remaining_balance: 3000,
    driver_id: "d3",
    driver_name: "Karim Tazi",
    pickup_time: "16:30",
    pickup_location: "Four Seasons Resort Marrakech",
    activity_type: "camel",
  },
  {
    id: "7",
    customer_name: "Yuki Tanaka",
    email: "yuki.tanaka@email.com",
    phone: "+212 690-1234-5678",
    package_title: "VIP Desert Experience",
    status: "pending",
    date: "2025-12-06",
    guests: 2,
    total_price: 12000,
    payment_status: "deposit",
    amount_paid: 3000,
    remaining_balance: 9000,
    activity_type: "quad",
  },
  {
    id: "8",
    customer_name: "Isabella Martinez",
    email: "isabella.m@email.com",
    phone: "+212 655 1234 5678",
    package_title: "Premium Sunset Tour",
    status: "confirmed",
    date: "2025-11-30",
    guests: 5,
    total_price: 20000,
    payment_status: "paid",
    amount_paid: 20000,
    remaining_balance: 0,
    driver_id: "d1",
    driver_name: "Hassan Amrani",
    pickup_time: "10:30",
    pickup_location: "Royal Mansour",
    activity_type: "camel",
  },
]

export const mockPackages: Package[] = [
  {
    id: "1",
    title: "Basic Discovery",
    description:
      "Perfect introduction to the Agafay Desert. Includes camel ride, traditional tea ceremony, and stunning sunset views.",
    price: 1500,
    duration: "4 hours",
    includes: ["Camel ride", "Tea ceremony", "Sunset viewing", "Photo opportunities"],
    tier: "basic",
    is_active: true,
  },
  {
    id: "2",
    title: "Premium Sunset Tour",
    description: "An elevated desert experience with gourmet dining under the stars and exclusive camp access.",
    price: 4000,
    duration: "6 hours",
    includes: ["Camel ride", "Gourmet dinner", "Private camp", "Live music", "Stargazing"],
    tier: "premium",
    is_active: true,
  },
  {
    id: "3",
    title: "VIP Desert Experience",
    description:
      "The ultimate luxury desert adventure with private chef, premium accommodations, and personalized itinerary.",
    price: 6000,
    duration: "Full day",
    includes: [
      "Private transport",
      "Personal guide",
      "Private chef",
      "Luxury tent",
      "Spa treatment",
      "Helicopter option",
    ],
    tier: "vip",
    is_active: true,
  },
]

export const mockStats: DashboardStats = {
  total_revenue: 1568000,
  active_bookings: 24,
  pending_inquiries: 8,
  revenue_change: 12.5,
  bookings_change: 8.3,
  inquiries_change: -3.2,
  cash_collected: 1234500,
  pending_balance: 333500,
}

export const mockSchedule: ScheduleItem[] = [
  {
    id: "1",
    booking_id: "3",
    time: "09:00",
    customer_name: "Sofia Rodriguez",
    package_title: "Basic Discovery",
    guests: 6,
    driver_name: "Hassan Amrani",
    driver_phone: "+212 661 234 567",
    pickup_location: "Riad Jnane Mogador, Marrakech",
    customer_phone: "+212 612 345 678",
    special_notes: "Family with 2 children. Please bring extra water.",
    activity_type: "camel",
    payment_status: "paid",
  },
  {
    id: "2",
    booking_id: "8",
    time: "10:30",
    customer_name: "Isabella Martinez",
    package_title: "Premium Sunset Tour",
    guests: 5,
    driver_name: "Hassan Amrani",
    driver_phone: "+212 661 234 567",
    pickup_location: "Royal Mansour",
    customer_phone: "+212 655 1234 5678",
    special_notes: "VIP guests - ensure premium service.",
    activity_type: "camel",
    payment_status: "paid",
  },
  {
    id: "3",
    booking_id: "1",
    time: "14:00",
    customer_name: "Alexandra Chen",
    package_title: "VIP Desert Experience",
    guests: 4,
    driver_name: "Youssef Benali",
    driver_phone: "+212 662 345 678",
    pickup_location: "La Mamounia Hotel",
    customer_phone: "+212 655-0123",
    special_notes: "Anniversary celebration. Champagne already arranged.",
    activity_type: "camel",
    payment_status: "paid",
  },
  {
    id: "4",
    booking_id: "6",
    time: "16:30",
    customer_name: "Oliver Schmidt",
    package_title: "Basic Discovery",
    guests: 3,
    driver_name: "Karim Tazi",
    driver_phone: "+212 663 456 789",
    pickup_location: "Four Seasons Resort Marrakech",
    customer_phone: "+212 661 12345678",
    special_notes: "Vegetarian dietary requirements. Balance: 3,000 MAD pending.",
    activity_type: "camel",
    payment_status: "deposit",
  },
]

export const mockTrends: BookingTrend[] = [
  { date: "Mon", bookings: 12, revenue: 48000 },
  { date: "Tue", bookings: 18, revenue: 72000 },
  { date: "Wed", bookings: 15, revenue: 60000 },
  { date: "Thu", bookings: 22, revenue: 88000 },
  { date: "Fri", bookings: 28, revenue: 112000 },
  { date: "Sat", bookings: 35, revenue: 140000 },
  { date: "Sun", bookings: 30, revenue: 120000 },
]

export const mockActivities: Activity[] = [
  {
    id: "1",
    title: "Quad Biking",
    description: "Thrilling quad bike adventure through the desert dunes",
    price: 800,
    duration: "2 hours",
    is_active: true,
    resource_type: "quad",
    capacity_per_session: 20,
  },
  {
    id: "2",
    title: "Camel Ride",
    description: "Traditional camel trek with stunning views",
    price: 400,
    duration: "1.5 hours",
    is_active: true,
    resource_type: "camel",
    capacity_per_session: 30,
  },
  {
    id: "3",
    title: "Hot Air Balloon",
    description: "Sunrise balloon flight over the Agafay Desert",
    price: 2500,
    duration: "3 hours",
    is_active: true,
    resource_type: "balloon",
    capacity_per_session: 8,
  },
  {
    id: "4",
    title: "Horseback Riding",
    description: "Scenic horseback journey through desert landscapes",
    price: 600,
    duration: "2 hours",
    is_active: false,
    resource_type: "horse",
    capacity_per_session: 15,
  },
  {
    id: "5",
    title: "Buggy Tour",
    description: "High-speed buggy adventure in the desert",
    price: 1200,
    duration: "2.5 hours",
    is_active: true,
    resource_type: "buggy",
    capacity_per_session: 8,
  },
  {
    id: "6",
    title: "Yoga Retreat",
    description: "Peaceful yoga session at sunrise or sunset",
    price: 500,
    duration: "1.5 hours",
    is_active: true,
    resource_type: "none",
    capacity_per_session: 50,
  },
]

export const mockBlogPosts: BlogPost[] = [
  {
    id: "1",
    title: "Top 10 Desert Activities for Adventure Seekers",
    excerpt: "Discover the most thrilling experiences in the Agafay Desert...",
    content: "Full article content here...",
    date: "2025-11-28",
    status: "published",
    author: "Sarah Mitchell",
  },
  {
    id: "2",
    title: "A Guide to Luxury Desert Dining",
    excerpt: "Experience world-class cuisine under the Moroccan stars...",
    content: "Full article content here...",
    date: "2025-11-25",
    status: "published",
    author: "Sarah Mitchell",
  },
  {
    id: "3",
    title: "Planning Your Perfect Desert Getaway",
    excerpt: "Everything you need to know before visiting Agafay...",
    content: "Full article content here...",
    date: "2025-11-20",
    status: "draft",
    author: "Sarah Mitchell",
  },
  {
    id: "4",
    title: "Sunset Photography Tips for the Desert",
    excerpt: "Capture stunning moments with these professional tips...",
    content: "Full article content here...",
    date: "2025-11-15",
    status: "published",
    author: "Sarah Mitchell",
  },
  {
    id: "5",
    title: "The History of the Agafay Desert",
    excerpt: "Learn about the rich cultural heritage of this magical place...",
    content: "Full article content here...",
    date: "2025-11-10",
    status: "draft",
    author: "Sarah Mitchell",
  },
]

export const mockTestimonials: Testimonial[] = [
  {
    id: "1",
    customer_name: "Emily Watson",
    content:
      "Absolutely magical experience! The VIP package exceeded all expectations. The private chef prepared an incredible dinner under the stars.",
    rating: 5,
    date: "2025-11-27",
    status: "approved",
  },
  {
    id: "2",
    customer_name: "David Chen",
    content: "Our family had an amazing time on the Basic Discovery tour. The kids loved the camel ride!",
    rating: 5,
    date: "2025-11-25",
    status: "approved",
  },
  {
    id: "3",
    customer_name: "Marie Dubois",
    content: "The sunset views were breathtaking. Highly recommend the Premium Sunset Tour for couples.",
    rating: 4,
    date: "2025-11-22",
    status: "pending",
  },
  {
    id: "4",
    customer_name: "Ahmed Hassan",
    content: "Good experience but the pickup was 30 minutes late.",
    rating: 3,
    date: "2025-11-20",
    status: "pending",
  },
  {
    id: "5",
    customer_name: "Lisa Thompson",
    content: "A once-in-a-lifetime experience. The staff went above and beyond to make our anniversary special.",
    rating: 5,
    date: "2025-11-18",
    status: "approved",
  },
]

export function getAvailability(
  date: string,
  activityType: string,
  bookings: Booking[],
  resources: Resource[],
  activities: Activity[],
): { available: number; total: number } {
  const resource = resources.find((r) => r.type === activityType)
  const activity = activities.find((a) => a.resource_type === activityType)

  if (!resource || !activity) {
    return { available: 99, total: 99 }
  }

  const bookedGuests = bookings
    .filter((b) => b.date === date && b.activity_type === activityType && b.status !== "cancelled")
    .reduce((sum, b) => sum + b.guests, 0)

  return {
    available: Math.max(0, resource.total_count - bookedGuests),
    total: resource.total_count,
  }
}
